//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestClassesForPostgres
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Class_bool.
    /// </summary>
    // *** Start programmer edit section *** (Class_bool CustomAttributes)

    // *** End programmer edit section *** (Class_bool CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Class_bool : ICSSoft.STORMNET.DataObject
    {
        
        private bool fAttr;
        
        // *** Start programmer edit section *** (Class_bool CustomMembers)

        // *** End programmer edit section *** (Class_bool CustomMembers)

        
        /// <summary>
        /// Attr.
        /// </summary>
        // *** Start programmer edit section *** (Class_bool.Attr CustomAttributes)

        // *** End programmer edit section *** (Class_bool.Attr CustomAttributes)
        public virtual bool Attr
        {
            get
            {
                // *** Start programmer edit section *** (Class_bool.Attr Get start)

                // *** End programmer edit section *** (Class_bool.Attr Get start)
                bool result = this.fAttr;
                // *** Start programmer edit section *** (Class_bool.Attr Get end)

                // *** End programmer edit section *** (Class_bool.Attr Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class_bool.Attr Set start)

                // *** End programmer edit section *** (Class_bool.Attr Set start)
                this.fAttr = value;
                // *** Start programmer edit section *** (Class_bool.Attr Set end)

                // *** End programmer edit section *** (Class_bool.Attr Set end)
            }
        }
    }
}
