//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestClassesForPostgres
{
    using ICSSoft.STORMNET;

    using System;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Class_DateOnly.
    /// </summary>
    // *** Start programmer edit section *** (Class_DateOnly CustomAttributes)

    // *** End programmer edit section *** (Class_DateOnly CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Class_DateOnly : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fAttrDate;

#if NET6_0_OR_GREATER
        private System.DateOnly fAttrDateOnly;
#else
        private System.DateTime fAttrDateOnly;
#endif

        private string fAttrString;

#if NET6_0_OR_GREATER
        private System.TimeOnly fAttrTimeOnly;
#else
        private System.DateTime fAttrTimeOnly;
#endif

#if NET6_0_OR_GREATER
        private System.DateOnly? fAttrDateOnlyNullable;

        private System.TimeOnly? fAttrTimeOnlyNullable;
#endif

        // *** Start programmer edit section *** (Class_DateOnly CustomMembers)

        // *** End programmer edit section *** (Class_DateOnly CustomMembers)


        /// <summary>
        /// AttrDate.
        /// </summary>
        // *** Start programmer edit section *** (Class_DateOnly.AttrDate CustomAttributes)

        // *** End programmer edit section *** (Class_DateOnly.AttrDate CustomAttributes)
        public virtual System.DateTime AttrDate
        {
            get
            {
                // *** Start programmer edit section *** (Class_DateOnly.AttrDate Get start)

                // *** End programmer edit section *** (Class_DateOnly.AttrDate Get start)
                System.DateTime result = this.fAttrDate;
                // *** Start programmer edit section *** (Class_DateOnly.AttrDate Get end)

                // *** End programmer edit section *** (Class_DateOnly.AttrDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class_DateOnly.AttrDate Set start)

                // *** End programmer edit section *** (Class_DateOnly.AttrDate Set start)
                this.fAttrDate = value;
                // *** Start programmer edit section *** (Class_DateOnly.AttrDate Set end)

                // *** End programmer edit section *** (Class_DateOnly.AttrDate Set end)
            }
        }

        /// <summary>
        /// AttrDateOnly.
        /// </summary>
        // *** Start programmer edit section *** (Class_DateOnly.AttrDateOnly CustomAttributes)

        // *** End programmer edit section *** (Class_DateOnly.AttrDateOnly CustomAttributes)
#if NET6_0_OR_GREATER
        public virtual System.DateOnly AttrDateOnly
#else
        public virtual System.DateTime AttrDateOnly
#endif
        {
            get
            {
                // *** Start programmer edit section *** (Class_DateOnly.AttrDateOnly Get start)

                // *** End programmer edit section *** (Class_DateOnly.AttrDateOnly Get start)
#if NET6_0_OR_GREATER
                System.DateOnly result = this.fAttrDateOnly;
#else
                System.DateTime result = this.fAttrDateOnly;
#endif
                // *** Start programmer edit section *** (Class_DateOnly.AttrDateOnly Get end)

                // *** End programmer edit section *** (Class_DateOnly.AttrDateOnly Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class_DateOnly.AttrDateOnly Set start)

                // *** End programmer edit section *** (Class_DateOnly.AttrDateOnly Set start)
                this.fAttrDateOnly = value;
                // *** Start programmer edit section *** (Class_DateOnly.AttrDateOnly Set end)

                // *** End programmer edit section *** (Class_DateOnly.AttrDateOnly Set end)
            }
        }

        /// <summary>
        /// AttrString.
        /// </summary>
        // *** Start programmer edit section *** (Class_DateOnly.AttrString CustomAttributes)

        // *** End programmer edit section *** (Class_DateOnly.AttrString CustomAttributes)
        [StrLen(255)]
        public virtual string AttrString
        {
            get
            {
                // *** Start programmer edit section *** (Class_DateOnly.AttrString Get start)

                // *** End programmer edit section *** (Class_DateOnly.AttrString Get start)
                string result = this.fAttrString;
                // *** Start programmer edit section *** (Class_DateOnly.AttrString Get end)

                // *** End programmer edit section *** (Class_DateOnly.AttrString Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class_DateOnly.AttrString Set start)

                // *** End programmer edit section *** (Class_DateOnly.AttrString Set start)
                this.fAttrString = value;
                // *** Start programmer edit section *** (Class_DateOnly.AttrString Set end)

                // *** End programmer edit section *** (Class_DateOnly.AttrString Set end)
            }
        }

        /// <summary>
        /// AttrTimeOnly.
        /// </summary>
        // *** Start programmer edit section *** (Class_DateOnly.AttrTimeOnly CustomAttributes)

        // *** End programmer edit section *** (Class_DateOnly.AttrTimeOnly CustomAttributes)
#if NET6_0_OR_GREATER
        public virtual System.TimeOnly AttrTimeOnly
#else
        public virtual System.DateTime AttrTimeOnly
#endif
        {
            get
            {
                // *** Start programmer edit section *** (Class_DateOnly.AttrTimeOnly Get start)

                // *** End programmer edit section *** (Class_DateOnly.AttrTimeOnly Get start)
#if NET6_0_OR_GREATER
                System.TimeOnly result = this.fAttrTimeOnly;
#else
                System.DateTime result = this.fAttrTimeOnly;
#endif
                // *** Start programmer edit section *** (Class_DateOnly.AttrTimeOnly Get end)

                // *** End programmer edit section *** (Class_DateOnly.AttrTimeOnly Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class_DateOnly.AttrTimeOnly Set start)

                // *** Start programmer edit section *** (Class_DateOnly.AttrTimeOnly Set start)
                this.fAttrTimeOnly = value;
                // *** Start programmer edit section *** (Class_DateOnly.AttrTimeOnly Set end)

                // *** End programmer edit section *** (Class_DateOnly.AttrTimeOnly Set end)
            }
        }

#if NET6_0_OR_GREATER
        /// <summary>
        /// AttrDateOnlyNullable.
        /// </summary>
        public virtual System.DateOnly? AttrDateOnlyNullable
        {
            get
            {
                return this.fAttrDateOnlyNullable;
            }

            set
            {
                this.fAttrDateOnlyNullable = value;
            }
        }

        /// <summary>
        /// AttrTimeOnlyNullable.
        /// </summary>
        public virtual System.TimeOnly? AttrTimeOnlyNullable
        {
            get
            {
                return this.fAttrTimeOnlyNullable;
            }

            set
            {
                this.fAttrTimeOnlyNullable = value;
            }
        }
#endif
    }
}

