//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestClassesForPostgres
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DetailClass2.
    /// </summary>
    // *** Start programmer edit section *** (DetailClass2 CustomAttributes)

    // *** End programmer edit section *** (DetailClass2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class DetailClass2 : ICSSoft.STORMNET.DataObject
    {
        
        private string fDetailAttr2;
        
        private IIS.TestClassesForPostgres.DetailClass fDetailClass;
        
        // *** Start programmer edit section *** (DetailClass2 CustomMembers)

        // *** End programmer edit section *** (DetailClass2 CustomMembers)

        
        /// <summary>
        /// DetailAttr2.
        /// </summary>
        // *** Start programmer edit section *** (DetailClass2.DetailAttr2 CustomAttributes)

        // *** End programmer edit section *** (DetailClass2.DetailAttr2 CustomAttributes)
        [StrLen(255)]
        public virtual string DetailAttr2
        {
            get
            {
                // *** Start programmer edit section *** (DetailClass2.DetailAttr2 Get start)

                // *** End programmer edit section *** (DetailClass2.DetailAttr2 Get start)
                string result = this.fDetailAttr2;
                // *** Start programmer edit section *** (DetailClass2.DetailAttr2 Get end)

                // *** End programmer edit section *** (DetailClass2.DetailAttr2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailClass2.DetailAttr2 Set start)

                // *** End programmer edit section *** (DetailClass2.DetailAttr2 Set start)
                this.fDetailAttr2 = value;
                // *** Start programmer edit section *** (DetailClass2.DetailAttr2 Set end)

                // *** End programmer edit section *** (DetailClass2.DetailAttr2 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.TestClassesForPostgres.DetailClass.
        /// </summary>
        // *** Start programmer edit section *** (DetailClass2.DetailClass CustomAttributes)

        // *** End programmer edit section *** (DetailClass2.DetailClass CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage("DetailClass")]
        [TypeUsage(new string[] {
                "IIS.TestClassesForPostgres.DetailClass",
                "IIS.TestClassesForPostgres.ДетейлКлассДлинноеИмя",
                "IIS.TestClassesForPostgres.ДетейлКлассДлинноеИмя2"})]
        public virtual IIS.TestClassesForPostgres.DetailClass DetailClass
        {
            get
            {
                // *** Start programmer edit section *** (DetailClass2.DetailClass Get start)

                // *** End programmer edit section *** (DetailClass2.DetailClass Get start)
                IIS.TestClassesForPostgres.DetailClass result = this.fDetailClass;
                // *** Start programmer edit section *** (DetailClass2.DetailClass Get end)

                // *** End programmer edit section *** (DetailClass2.DetailClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailClass2.DetailClass Set start)

                // *** End programmer edit section *** (DetailClass2.DetailClass Set start)
                this.fDetailClass = value;
                // *** Start programmer edit section *** (DetailClass2.DetailClass Set end)

                // *** End programmer edit section *** (DetailClass2.DetailClass Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of DetailClass2.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDetailClass2 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfDetailClass2 CustomAttributes)
    public class DetailArrayOfDetailClass2 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.TestClassesForPostgres.DetailArrayOfDetailClass2 members)

        // *** End programmer edit section *** (IIS.TestClassesForPostgres.DetailArrayOfDetailClass2 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type DetailClass2 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type DetailClass2.
        /// </summary>
        public DetailArrayOfDetailClass2(IIS.TestClassesForPostgres.DetailClass fDetailClass) : 
                base(typeof(DetailClass2), ((ICSSoft.STORMNET.DataObject)(fDetailClass)))
        {
        }
        
        public IIS.TestClassesForPostgres.DetailClass2 this[int index]
        {
            get
            {
                return ((IIS.TestClassesForPostgres.DetailClass2)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.TestClassesForPostgres.DetailClass2 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
