language: csharp
solution: Flexberry ORM.sln
dotnet: 3.1
mono: latest
env:
  global:
    - CONFIGURATION: Debug
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
addons:
  apt:
    packages:
      - doxygen
services:
  - postgresql
install:
  - nuget restore "Flexberry ORM.sln" -NonInteractive
  - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory packages
script:
  - msbuild /verbosity:quiet /p:WarningLevel=0 /p:Configuration=$CONFIGURATION "Flexberry ORM.sln"
  - mono ./packages/xunit.runner.console.2.4.1/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.ORM.Tests/bin/$CONFIGURATION/net461/NewPlatform.Flexberry.ORM.Tests.dll
  - mono ./packages/xunit.runner.console.2.4.1/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.ORM.IntegratedTests/bin/$CONFIGURATION/net461/NewPlatform.Flexberry.ORM.IntegratedTests.dll
  - dotnet test ./NewPlatform.Flexberry.ORM.Tests/bin/$CONFIGURATION/netcoreapp3.1/NewPlatform.Flexberry.ORM.Tests.dll
  - dotnet test ./NewPlatform.Flexberry.ORM.IntegratedTests/bin/$CONFIGURATION/netcoreapp3.1/NewPlatform.Flexberry.ORM.IntegratedTests.dll
after_success:
  - test $TRAVIS_PULL_REQUEST == "false"
    && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_BRANCH == "develop")
    && bash Doxygen/update-autodoc.sh
