var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_data_object =
[
    [ "OrderPropertyTest", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_data_object_1_1_order_property_test.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_data_object_1_1_order_property_test" ]
];