var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_functional_language =
[
    [ "LoadCharTest", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_functional_language_1_1_load_char_test.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_functional_language_1_1_load_char_test" ]
];