var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_tests_1_1_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business =
[
    [ "LINQProvider", "namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_tests_1_1_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_l_i_n_q_provider.html", "namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_tests_1_1_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_l_i_n_q_provider" ]
];