//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CaseSensitiveEnum.
    /// </summary>
    // *** Start programmer edit section *** (CaseSensitiveEnum CustomAttributes)

    // *** End programmer edit section *** (CaseSensitiveEnum CustomAttributes)
    public enum CaseSensitiveEnum
    {
        
        // *** Start programmer edit section *** (CaseSensitiveEnum.Year9998 CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.Year9998 CustomAttributes)
        [Caption("LAST DAY")]
        Year9998,
        
        // *** Start programmer edit section *** (CaseSensitiveEnum.Year9999 CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.Year9999 CustomAttributes)
        [Caption("Last day")]
        Year9999,
        
        // *** Start programmer edit section *** (CaseSensitiveEnum.CaseInsensitive CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.CaseInsensitive CustomAttributes)
        [Caption("CasEinSenSitiVe")]
        CaseInsensitive,
        
        // *** Start programmer edit section *** (CaseSensitiveEnum.CaseINSENSITIVEVAL CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.CaseINSENSITIVEVAL CustomAttributes)
        [Caption("")]
        CaseINSENSITIVEVAL,
        
        // *** Start programmer edit section *** (CaseSensitiveEnum.CASEINSENSITIVEVAL CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.CASEINSENSITIVEVAL CustomAttributes)
        CASEINSENSITIVEVAL,
    }
}
