//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CaseSensitiveEnum.
    /// </summary>
    // *** Start programmer edit section *** (CaseSensitiveEnum CustomAttributes)

    // *** End programmer edit section *** (CaseSensitiveEnum CustomAttributes)
    public enum CaseSensitiveEnum
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (CaseSensitiveEnum.Year9998 CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.Year9998 CustomAttributes)
        [Caption("LAST DAY")]
        Year9998,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (CaseSensitiveEnum.Year9999 CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.Year9999 CustomAttributes)
        [Caption("Last day")]
        Year9999,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (CaseSensitiveEnum.CaseInsensitive CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.CaseInsensitive CustomAttributes)
        [Caption("CasEinSenSitiVe")]
        CaseInsensitive,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (CaseSensitiveEnum.CaseINSENSITIVEVAL CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.CaseINSENSITIVEVAL CustomAttributes)
        [Caption("")]
        CaseINSENSITIVEVAL,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (CaseSensitiveEnum.CASEINSENSITIVEVAL CustomAttributes)

        // *** End programmer edit section *** (CaseSensitiveEnum.CASEINSENSITIVEVAL CustomAttributes)
        CASEINSENSITIVEVAL,
    }
}
