//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ClassWithMaster.
    /// </summary>
    // *** Start programmer edit section *** (ClassWithMaster CustomAttributes)

    // *** End programmer edit section *** (ClassWithMaster CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ClassWithMasterE", new string[] {
            "Name",
            "First",
            "First.Name",
            "Second",
            "Second.Name"})]
    public class ClassWithMaster : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private NewPlatform.Flexberry.ORM.Tests.ClassToTestIRND fFirst;
        
        private NewPlatform.Flexberry.ORM.Tests.ClassToTestIRCD fSecond;
        
        // *** Start programmer edit section *** (ClassWithMaster CustomMembers)

        // *** End programmer edit section *** (ClassWithMaster CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ClassWithMaster.Name CustomAttributes)

        // *** End programmer edit section *** (ClassWithMaster.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ClassWithMaster.Name Get start)

                // *** End programmer edit section *** (ClassWithMaster.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ClassWithMaster.Name Get end)

                // *** End programmer edit section *** (ClassWithMaster.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassWithMaster.Name Set start)

                // *** End programmer edit section *** (ClassWithMaster.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ClassWithMaster.Name Set end)

                // *** End programmer edit section *** (ClassWithMaster.Name Set end)
            }
        }
        
        /// <summary>
        /// ClassWithMaster.
        /// </summary>
        // *** Start programmer edit section *** (ClassWithMaster.First CustomAttributes)

        // *** End programmer edit section *** (ClassWithMaster.First CustomAttributes)
        [PropertyStorage(new string[] {
                "First"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.Tests.ClassToTestIRND First
        {
            get
            {
                // *** Start programmer edit section *** (ClassWithMaster.First Get start)

                // *** End programmer edit section *** (ClassWithMaster.First Get start)
                NewPlatform.Flexberry.ORM.Tests.ClassToTestIRND result = this.fFirst;
                // *** Start programmer edit section *** (ClassWithMaster.First Get end)

                // *** End programmer edit section *** (ClassWithMaster.First Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassWithMaster.First Set start)

                // *** End programmer edit section *** (ClassWithMaster.First Set start)
                this.fFirst = value;
                // *** Start programmer edit section *** (ClassWithMaster.First Set end)

                // *** End programmer edit section *** (ClassWithMaster.First Set end)
            }
        }
        
        /// <summary>
        /// ClassWithMaster.
        /// </summary>
        // *** Start programmer edit section *** (ClassWithMaster.Second CustomAttributes)

        // *** End programmer edit section *** (ClassWithMaster.Second CustomAttributes)
        [PropertyStorage(new string[] {
                "Second"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.Tests.ClassToTestIRCD Second
        {
            get
            {
                // *** Start programmer edit section *** (ClassWithMaster.Second Get start)

                // *** End programmer edit section *** (ClassWithMaster.Second Get start)
                NewPlatform.Flexberry.ORM.Tests.ClassToTestIRCD result = this.fSecond;
                // *** Start programmer edit section *** (ClassWithMaster.Second Get end)

                // *** End programmer edit section *** (ClassWithMaster.Second Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassWithMaster.Second Set start)

                // *** End programmer edit section *** (ClassWithMaster.Second Set start)
                this.fSecond = value;
                // *** Start programmer edit section *** (ClassWithMaster.Second Set end)

                // *** End programmer edit section *** (ClassWithMaster.Second Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ClassWithMasterE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassWithMasterE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassWithMasterE", typeof(NewPlatform.Flexberry.ORM.Tests.ClassWithMaster));
                }
            }
        }
    }
}
