//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Dish2.
    /// </summary>
    //  *** Start programmer edit section *** (Dish2 CustomAttributes)

    //  *** End programmer edit section *** (Dish2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Dish2E", new string[] {
            "DishName as \'Dish name\'",
            "MainIngridient as \'Main ingridient\'",
            "MainIngridient.Name as \'Name\'"})]
    [View("Dish2L", new string[] {
            "DishName as \'Dish name\'",
            "MainIngridient.Name as \'Name\'"})]
    public class Dish2 : ICSSoft.STORMNET.DataObject
    {
        
        private string fDishName;
        
        private NewPlatform.Flexberry.ORM.Tests.Plant2 fMainIngridient;
        
        //  *** Start programmer edit section *** (Dish2 CustomMembers)

        //  *** End programmer edit section *** (Dish2 CustomMembers)

        
        /// <summary>
        /// DishName.
        /// </summary>
        //  *** Start programmer edit section *** (Dish2.DishName CustomAttributes)

        //  *** End programmer edit section *** (Dish2.DishName CustomAttributes)
        [StrLen(255)]
        public virtual string DishName
        {
            get
            {
                //  *** Start programmer edit section *** (Dish2.DishName Get start)

                //  *** End programmer edit section *** (Dish2.DishName Get start)
                string result = this.fDishName;
                //  *** Start programmer edit section *** (Dish2.DishName Get end)

                //  *** End programmer edit section *** (Dish2.DishName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Dish2.DishName Set start)

                //  *** End programmer edit section *** (Dish2.DishName Set start)
                this.fDishName = value;
                //  *** Start programmer edit section *** (Dish2.DishName Set end)

                //  *** End programmer edit section *** (Dish2.DishName Set end)
            }
        }
        
        /// <summary>
        /// Dish2.
        /// </summary>
        //  *** Start programmer edit section *** (Dish2.MainIngridient CustomAttributes)

        //  *** End programmer edit section *** (Dish2.MainIngridient CustomAttributes)
        [PropertyStorage("MainIngridient")]
        [TypeUsage(new string[] {
                "NewPlatform.Flexberry.ORM.Tests.Cabbage2",
                "NewPlatform.Flexberry.ORM.Tests.Plant2"})]
        public virtual NewPlatform.Flexberry.ORM.Tests.Plant2 MainIngridient
        {
            get
            {
                //  *** Start programmer edit section *** (Dish2.MainIngridient Get start)

                //  *** End programmer edit section *** (Dish2.MainIngridient Get start)
                NewPlatform.Flexberry.ORM.Tests.Plant2 result = this.fMainIngridient;
                //  *** Start programmer edit section *** (Dish2.MainIngridient Get end)

                //  *** End programmer edit section *** (Dish2.MainIngridient Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Dish2.MainIngridient Set start)

                //  *** End programmer edit section *** (Dish2.MainIngridient Set start)
                this.fMainIngridient = value;
                //  *** Start programmer edit section *** (Dish2.MainIngridient Set end)

                //  *** End programmer edit section *** (Dish2.MainIngridient Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Dish2E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Dish2E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Dish2E", typeof(NewPlatform.Flexberry.ORM.Tests.Dish2));
                }
            }
            
            /// <summary>
            /// "Dish2L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Dish2L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Dish2L", typeof(NewPlatform.Flexberry.ORM.Tests.Dish2));
                }
            }
        }
    }
}
