//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// FileForTests.
    /// </summary>
    // *** Start programmer edit section *** (FileForTests CustomAttributes)

    // *** End programmer edit section *** (FileForTests CustomAttributes)
    [ICSSoft.STORMNET.StoreInstancesInType(typeof(SQLDataService), typeof(string))]
    public class FileForTests : INotifyUpdateProperty
    {
        
        // *** Start programmer edit section *** (FileForTests CustomMembers)
        /// <inheritdoc cref="INotifyUpdateProperty"/>
        public void BeforeUpdateProperty(DataObject dataObject, ObjectStatus status, string propertyName, object oldValue, object newValue)
        {
            dataObject.DynamicProperties.Add(nameof(BeforeUpdateProperty), new Tuple<ObjectStatus, string, object, object>(status, propertyName, oldValue, newValue));
        }

        /// <inheritdoc cref="INotifyUpdateProperty"/>
        public void AfterSuccessSqlUpdateProperty(DataObject dataObject, ObjectStatus status, string propertyName, object oldValue, object newValue)
        {
            dataObject.DynamicProperties.Add(nameof(AfterSuccessSqlUpdateProperty), new Tuple<ObjectStatus, string, object, object>(status, propertyName, oldValue, newValue));
        }

        /// <inheritdoc cref="INotifyUpdateProperty"/>
        public void AfterSuccessUpdateProperty(DataObject dataObject, ObjectStatus status, string propertyName, object oldValue, object newValue)
        {
            dataObject.DynamicProperties.Add(nameof(AfterSuccessUpdateProperty), new Tuple<ObjectStatus, string, object, object>(status, propertyName, oldValue, newValue));
        }

        /// <inheritdoc cref="INotifyUpdateProperty"/>
        public void AfterFailUpdateProperty(DataObject dataObject, ObjectStatus status, string propertyName, object oldValue, object newValue)
        {
            dataObject.DynamicProperties.Add(nameof(AfterFailUpdateProperty), new Tuple<ObjectStatus, string, object, object>(status, propertyName, oldValue, newValue));
        }

        public string Value { get; set; }

        // *** End programmer edit section *** (FileForTests CustomMembers)

    }
}
