//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)
    using System.Collections.Generic;

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Homer.
    /// </summary>
    //  *** Start programmer edit section *** (Homer CustomAttributes)

    //  *** End programmer edit section *** (Homer CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Homer : ICSSoft.STORMNET.DataObject, INotifyUpdateObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (Homer CustomMembers)
        /// <inheritdoc cref="INotifyUpdateObject"/>
        public void BeforeUpdateObject(DataObject dataObject, ObjectStatus status, IEnumerable<DataObject> dataObjects)
        {
            dataObject.DynamicProperties.Add(nameof(BeforeUpdateObject), new Tuple<ObjectStatus, IEnumerable<DataObject>>(status, dataObjects));
        }

        /// <inheritdoc cref="INotifyUpdateObject"/>
        public void AfterSuccessSqlUpdateObject(DataObject dataObject, ObjectStatus status, IEnumerable<DataObject> dataObjects)
        {
            dataObject.DynamicProperties.Add(nameof(AfterSuccessSqlUpdateObject), new Tuple<ObjectStatus, IEnumerable<DataObject>>(status, dataObjects));
        }

        /// <inheritdoc cref="INotifyUpdateObject"/>
        public void AfterSuccessUpdateObject(DataObject dataObject, ObjectStatus status, IEnumerable<DataObject> dataObjects)
        {
            dataObject.DynamicProperties.Add(nameof(AfterSuccessUpdateObject), new Tuple<ObjectStatus, IEnumerable<DataObject>>(status, dataObjects));
        }

        /// <inheritdoc cref="INotifyUpdateObject"/>
        public void AfterFailUpdateObject(DataObject dataObject, ObjectStatus status, IEnumerable<DataObject> dataObjects)
        {
            dataObject.DynamicProperties.Add(nameof(AfterFailUpdateObject), new Tuple<ObjectStatus, IEnumerable<DataObject>>(status, dataObjects));
        }

        //  *** End programmer edit section *** (Homer CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Homer.Name CustomAttributes)

        //  *** End programmer edit section *** (Homer.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Homer.Name Get start)

                //  *** End programmer edit section *** (Homer.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Homer.Name Get end)

                //  *** End programmer edit section *** (Homer.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Homer.Name Set start)

                //  *** End programmer edit section *** (Homer.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Homer.Name Set end)

                //  *** End programmer edit section *** (Homer.Name Set end)
            }
        }
    }
}
