//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// InheritedMasterClass.
    /// </summary>
    // *** Start programmer edit section *** (InheritedMasterClass CustomAttributes)

    // *** End programmer edit section *** (InheritedMasterClass CustomAttributes)
    [ClassStorage("MasterClass")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class InheritedMasterClass : MasterClass
    {

        // *** Start programmer edit section *** (InheritedMasterClass CustomMembers)

        // *** End programmer edit section *** (InheritedMasterClass CustomMembers)
    }
}
