//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// InheritedMasterClass.
    /// </summary>
    // *** Start programmer edit section *** (InheritedMasterClass CustomAttributes)

    // *** End programmer edit section *** (InheritedMasterClass CustomAttributes)
    [ClassStorage("MasterClass")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class InheritedMasterClass : NewPlatform.Flexberry.ORM.Tests.MasterClass
    {
        
        // *** Start programmer edit section *** (InheritedMasterClass CustomMembers)

        // *** End programmer edit section *** (InheritedMasterClass CustomMembers)

    }
}
