//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using System.Collections.Generic;
    using System.Linq;

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NotifyUpdateObjectsGeneratedMock.
    /// </summary>
    //  *** Start programmer edit section *** (NotifyUpdateObjectsGeneratedMock CustomAttributes)

    //  *** End programmer edit section *** (NotifyUpdateObjectsGeneratedMock CustomAttributes)
    public class NotifyUpdateObjectsGeneratedMock : INotifyUpdateObjects
    {
        
        //  *** Start programmer edit section *** (NotifyUpdateObjectsGeneratedMock CustomMembers)
        /// <inheritdoc cref="INotifyUpdateObjects"/>
        public void BeforeUpdateObjects(Guid operationId, IDataService dataService, System.Data.IDbTransaction transaction, IEnumerable<DataObject> dataObjects)
        {
            var dataObject = dataObjects.First();

            dataObject.DynamicProperties.Add(nameof(BeforeUpdateObjects), new Tuple<Guid, IDataService, System.Data.IDbTransaction, IEnumerable<DataObject>>(operationId, dataService, transaction, dataObjects));
        }

        /// <inheritdoc cref="INotifyUpdateObjects"/>
        public void AfterSuccessSqlUpdateObjects(Guid operationId, IDataService dataService, System.Data.IDbTransaction transaction, IEnumerable<DataObject> dataObjects)
        {
            var dataObject = dataObjects.First();

            dataObject.DynamicProperties.Add(nameof(AfterSuccessSqlUpdateObjects), new Tuple<Guid, IDataService, System.Data.IDbTransaction, IEnumerable<DataObject>>(operationId, dataService, transaction, dataObjects));
        }

        /// <inheritdoc cref="INotifyUpdateObjects"/>
        public void AfterSuccessUpdateObjects(Guid operationId, IDataService dataService, IEnumerable<DataObject> dataObjects)
        {
            var dataObject = dataObjects.First();

            dataObject.DynamicProperties.Add(nameof(AfterSuccessUpdateObjects), new Tuple<Guid, IDataService, IEnumerable<DataObject>>(operationId, dataService, dataObjects));
        }


        /// <inheritdoc cref="INotifyUpdateObjects"/>
        public void AfterFailUpdateObjects(Guid operationId, IDataService dataService, IEnumerable<DataObject> dataObjects)
        {
            var dataObject = dataObjects.First();

            dataObject.DynamicProperties.Add(nameof(AfterFailUpdateObjects), new Tuple<Guid, IDataService, IEnumerable<DataObject>>(operationId, dataService, dataObjects));
        }

        //  *** End programmer edit section *** (NotifyUpdateObjectsGeneratedMock CustomMembers)

    }
}
