//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NotStoredClass.
    /// </summary>
    //  *** Start programmer edit section *** (NotStoredClass CustomAttributes)

    //  *** End programmer edit section *** (NotStoredClass CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class NotStoredClass : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (NotStoredClass CustomMembers)

        //  *** End programmer edit section *** (NotStoredClass CustomMembers)

    }
}
