//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// PoleEnum.
    /// </summary>
    // *** Start programmer edit section *** (PoleEnum CustomAttributes)

    // *** End programmer edit section *** (PoleEnum CustomAttributes)
    public enum PoleEnum
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (PoleEnum.Attribute1 CustomAttributes)

        // *** End programmer edit section *** (PoleEnum.Attribute1 CustomAttributes)
        [Caption("GreateAttribute")]
        Attribute1,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (PoleEnum.Attribute2 CustomAttributes)

        // *** End programmer edit section *** (PoleEnum.Attribute2 CustomAttributes)
        Attribute2,
    }
}
