//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// SomeMasterClass.
    /// </summary>
    // *** Start programmer edit section *** (SomeMasterClass CustomAttributes)

    // *** End programmer edit section *** (SomeMasterClass CustomAttributes)
    [AutoAltered()]
    [Caption("Class A")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ClassAE", new string[] {
            "FieldA as \'Field A\'"})]
    [View("ClassAL", new string[] {
            "FieldA as \'Field A\'"})]
    public class SomeMasterClass : ICSSoft.STORMNET.DataObject
    {
        
        private string fFieldA;
        
        // *** Start programmer edit section *** (SomeMasterClass CustomMembers)

        // *** End programmer edit section *** (SomeMasterClass CustomMembers)

        
        /// <summary>
        /// FieldA.
        /// </summary>
        // *** Start programmer edit section *** (SomeMasterClass.FieldA CustomAttributes)

        // *** End programmer edit section *** (SomeMasterClass.FieldA CustomAttributes)
        [StrLen(255)]
        public virtual string FieldA
        {
            get
            {
                // *** Start programmer edit section *** (SomeMasterClass.FieldA Get start)

                // *** End programmer edit section *** (SomeMasterClass.FieldA Get start)
                string result = this.fFieldA;
                // *** Start programmer edit section *** (SomeMasterClass.FieldA Get end)

                // *** End programmer edit section *** (SomeMasterClass.FieldA Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SomeMasterClass.FieldA Set start)

                // *** End programmer edit section *** (SomeMasterClass.FieldA Set start)
                this.fFieldA = value;
                // *** Start programmer edit section *** (SomeMasterClass.FieldA Set end)

                // *** End programmer edit section *** (SomeMasterClass.FieldA Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ClassAE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassAE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassAE", typeof(NewPlatform.Flexberry.ORM.Tests.SomeMasterClass));
                }
            }
            
            /// <summary>
            /// "ClassAL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassAL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassAL", typeof(NewPlatform.Flexberry.ORM.Tests.SomeMasterClass));
                }
            }
        }
    }
}
