//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// TypeNameUsageProviderTestClass.
    /// </summary>
    //  *** Start programmer edit section *** (TypeNameUsageProviderTestClass CustomAttributes)

    //  *** End programmer edit section *** (TypeNameUsageProviderTestClass CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class TypeNameUsageProviderTestClass : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (TypeNameUsageProviderTestClass CustomMembers)

        //  *** End programmer edit section *** (TypeNameUsageProviderTestClass CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (TypeNameUsageProviderTestClass.Name CustomAttributes)

        //  *** End programmer edit section *** (TypeNameUsageProviderTestClass.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (TypeNameUsageProviderTestClass.Name Get start)

                //  *** End programmer edit section *** (TypeNameUsageProviderTestClass.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (TypeNameUsageProviderTestClass.Name Get end)

                //  *** End programmer edit section *** (TypeNameUsageProviderTestClass.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (TypeNameUsageProviderTestClass.Name Set start)

                //  *** End programmer edit section *** (TypeNameUsageProviderTestClass.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (TypeNameUsageProviderTestClass.Name Set end)

                //  *** End programmer edit section *** (TypeNameUsageProviderTestClass.Name Set end)
            }
        }
    }
}
