//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ВидКредита.
    /// </summary>
    //  *** Start programmer edit section *** (ВидКредита CustomAttributes)

    //  *** End programmer edit section *** (ВидКредита CustomAttributes)
    public enum ВидКредита
    {
        
        //  *** Start programmer edit section *** (ВидКредита.Потребительский CustomAttributes)

        //  *** End programmer edit section *** (ВидКредита.Потребительский CustomAttributes)
        Потребительский,
        
        //  *** Start programmer edit section *** (ВидКредита.Автокредит CustomAttributes)

        //  *** End programmer edit section *** (ВидКредита.Автокредит CustomAttributes)
        Автокредит,
        
        //  *** Start programmer edit section *** (ВидКредита.Ипотека CustomAttributes)

        //  *** End programmer edit section *** (ВидКредита.Ипотека CustomAttributes)
        Ипотека,
    }
}
