//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ДокументацияККонкурсу.
    /// </summary>
    // *** Start programmer edit section *** (ДокументацияККонкурсу CustomAttributes)

    // *** End programmer edit section *** (ДокументацияККонкурсу CustomAttributes)
    [ClassStorage("ДокККонкурсу")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокументацияККонкурсуE", new string[] {
            "Файл"})]
    public class ДокументацияККонкурсу : ICSSoft.STORMNET.DataObject
    {
        
        private ICSSoft.STORMNET.UserDataTypes.WebFile fФайл;
        
        private NewPlatform.Flexberry.ORM.Tests.Конкурс fКонкурс;
        
        // *** Start programmer edit section *** (ДокументацияККонкурсу CustomMembers)

        // *** End programmer edit section *** (ДокументацияККонкурсу CustomMembers)

        
        /// <summary>
        /// Файл.
        /// </summary>
        // *** Start programmer edit section *** (ДокументацияККонкурсу.Файл CustomAttributes)

        // *** End programmer edit section *** (ДокументацияККонкурсу.Файл CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.WebFile Файл
        {
            get
            {
                // *** Start programmer edit section *** (ДокументацияККонкурсу.Файл Get start)

                // *** End programmer edit section *** (ДокументацияККонкурсу.Файл Get start)
                ICSSoft.STORMNET.UserDataTypes.WebFile result = this.fФайл;
                // *** Start programmer edit section *** (ДокументацияККонкурсу.Файл Get end)

                // *** End programmer edit section *** (ДокументацияККонкурсу.Файл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокументацияККонкурсу.Файл Set start)

                // *** End programmer edit section *** (ДокументацияККонкурсу.Файл Set start)
                this.fФайл = value;
                // *** Start programmer edit section *** (ДокументацияККонкурсу.Файл Set end)

                // *** End programmer edit section *** (ДокументацияККонкурсу.Файл Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.Tests.Конкурс.
        /// </summary>
        // *** Start programmer edit section *** (ДокументацияККонкурсу.Конкурс CustomAttributes)

        // *** End programmer edit section *** (ДокументацияККонкурсу.Конкурс CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.Tests.Конкурс Конкурс
        {
            get
            {
                // *** Start programmer edit section *** (ДокументацияККонкурсу.Конкурс Get start)

                // *** End programmer edit section *** (ДокументацияККонкурсу.Конкурс Get start)
                NewPlatform.Flexberry.ORM.Tests.Конкурс result = this.fКонкурс;
                // *** Start programmer edit section *** (ДокументацияККонкурсу.Конкурс Get end)

                // *** End programmer edit section *** (ДокументацияККонкурсу.Конкурс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокументацияККонкурсу.Конкурс Set start)

                // *** End programmer edit section *** (ДокументацияККонкурсу.Конкурс Set start)
                this.fКонкурс = value;
                // *** Start programmer edit section *** (ДокументацияККонкурсу.Конкурс Set end)

                // *** End programmer edit section *** (ДокументацияККонкурсу.Конкурс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокументацияККонкурсуE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументацияККонкурсуE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументацияККонкурсуE", typeof(NewPlatform.Flexberry.ORM.Tests.ДокументацияККонкурсу));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ДокументацияККонкурсу.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfДокументацияККонкурсу CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfДокументацияККонкурсу CustomAttributes)
    public class DetailArrayOfДокументацияККонкурсу : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.Tests.DetailArrayOfДокументацияККонкурсу members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.Tests.DetailArrayOfДокументацияККонкурсу members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ДокументацияККонкурсу by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ДокументацияККонкурсу.
        /// </summary>
        public DetailArrayOfДокументацияККонкурсу(NewPlatform.Flexberry.ORM.Tests.Конкурс fКонкурс) : 
                base(typeof(ДокументацияККонкурсу), ((ICSSoft.STORMNET.DataObject)(fКонкурс)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.Tests.ДокументацияККонкурсу this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.Tests.ДокументацияККонкурсу)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.Tests.ДокументацияККонкурсу dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
