//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кошка.
    /// </summary>
    // *** Start programmer edit section *** (Кошка CustomAttributes)

    // *** End programmer edit section *** (Кошка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("k_КошкаE", new string[] {
            "Кличка as \'Кличка\'",
            "ДатаРождения as \'Дата рождения\'",
            "Порода as \'Порода\'",
            "Порода.Название as \'Название\'"})]
    [AssociatedDetailViewAttribute("k_КошкаE", "Лапа", "k_ЛапаE", true, "", "Лапа", true, new string[] {
            ""})]
    [View("k_КошкаL", new string[] {
            "Кличка as \'Кличка\'",
            "ДатаРождения as \'Дата рождения\'",
            "Порода.Название as \'Название\'"})]
    [View("КИЛ_КошкаE", new string[] {
            "Кличка on \'|Общее\'",
            "Порода on \'|Общее\'",
            "Порода.Название as \'Порода\' on \'|Общее\'",
            "ДатаРождения as \'Дата рождения\' on \'|Общее\'",
            "Тип on \'|Общее\'",
            "Агрессивная on \'|Общее\'",
            "ПородаСтрокой"})]
    [AssociatedDetailViewAttribute("КИЛ_КошкаE", "Лапа", "КИЛ_ЛапаE", false, "|Лапы", "", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("КИЛ_КошкаE", "Порода", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("КИЛ_КошкаL", new string[] {
            "Кличка",
            "Тип",
            "ДатаРождения",
            "ПородаСтрокой",
            "Агрессивная",
            "КоличествоУсовСлева",
            "КоличествоУсовСправа",
            "Порода",
            "Порода.Название"}, Hidden=new string[] {
            "Порода"})]
    [View("КошкаE", new string[] {
            "Кличка as \'Кличка\'",
            "ДатаРождения as \'Дата рождения\'",
            "Тип as \'Тип\'",
            "ПородаСтрокой as \'Порода строкой\'",
            "Агрессивная as \'Агрессивная\'",
            "Порода as \'Порода\'",
            "Порода.Название as \'Название\'",
            "Порода.ТипПороды",
            "Порода.ТипПороды.Название",
            "Порода.ТипПороды.ДатаРегистрации"})]
    [AssociatedDetailViewAttribute("КошкаE", "Лапа", "ЛапаE", true, "", "Лапа", true, new string[] {
            ""})]
    [View("КошкаGuid", new string[] {
            "Кличка",
            "Порода",
            "Порода.Название",
            "Порода.Ключ",
            "Ключ"})]
    [View("КошкаL", new string[] {
            "Кличка as \'Кличка\'",
            "ДатаРождения as \'Дата рождения\'",
            "Тип as \'Тип\'",
            "ПородаСтрокой as \'Порода строкой\'",
            "Агрессивная as \'Агрессивная\'",
            "Порода.Название as \'Название\'"})]
    public class Кошка : ICSSoft.STORMNET.DataObject
    {
        
        private string fКличка;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаРождения;
        
        private NewPlatform.Flexberry.ORM.Tests.ТипКошки fТип;
        
        private string fПородаСтрокой;
        
        private bool fАгрессивная;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt fКоличествоУсовСлева;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableInt fКоличествоУсовСправа;
        
        private ICSSoft.STORMNET.KeyGen.KeyGuid fКлюч;
        
        private NewPlatform.Flexberry.ORM.Tests.Порода fПорода;
        
        private NewPlatform.Flexberry.ORM.Tests.DetailArrayOfЛапа fЛапа;
        
        // *** Start programmer edit section *** (Кошка CustomMembers)

        // *** End programmer edit section *** (Кошка CustomMembers)

        
        /// <summary>
        /// Кличка.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Кличка CustomAttributes)

        // *** End programmer edit section *** (Кошка.Кличка CustomAttributes)
        [StrLen(255)]
        public virtual string Кличка
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Кличка Get start)

                // *** End programmer edit section *** (Кошка.Кличка Get start)
                string result = this.fКличка;
                // *** Start programmer edit section *** (Кошка.Кличка Get end)

                // *** End programmer edit section *** (Кошка.Кличка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Кличка Set start)

                // *** End programmer edit section *** (Кошка.Кличка Set start)
                this.fКличка = value;
                // *** Start programmer edit section *** (Кошка.Кличка Set end)

                // *** End programmer edit section *** (Кошка.Кличка Set end)
            }
        }
        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Кошка.ДатаРождения CustomAttributes)
        [NotNull()]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.ДатаРождения Get start)

                // *** End programmer edit section *** (Кошка.ДатаРождения Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Кошка.ДатаРождения Get end)

                // *** End programmer edit section *** (Кошка.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.ДатаРождения Set start)

                // *** End programmer edit section *** (Кошка.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Кошка.ДатаРождения Set end)

                // *** End programmer edit section *** (Кошка.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Тип CustomAttributes)

        // *** End programmer edit section *** (Кошка.Тип CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.Tests.ТипКошки Тип
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Тип Get start)

                // *** End programmer edit section *** (Кошка.Тип Get start)
                NewPlatform.Flexberry.ORM.Tests.ТипКошки result = this.fТип;
                // *** Start programmer edit section *** (Кошка.Тип Get end)

                // *** End programmer edit section *** (Кошка.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Тип Set start)

                // *** End programmer edit section *** (Кошка.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Кошка.Тип Set end)

                // *** End programmer edit section *** (Кошка.Тип Set end)
            }
        }
        
        /// <summary>
        /// ПородаСтрокой.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.ПородаСтрокой CustomAttributes)

        // *** End programmer edit section *** (Кошка.ПородаСтрокой CustomAttributes)
        [StrLen(255)]
        public virtual string ПородаСтрокой
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.ПородаСтрокой Get start)

                // *** End programmer edit section *** (Кошка.ПородаСтрокой Get start)
                string result = this.fПородаСтрокой;
                // *** Start programmer edit section *** (Кошка.ПородаСтрокой Get end)

                // *** End programmer edit section *** (Кошка.ПородаСтрокой Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.ПородаСтрокой Set start)

                // *** End programmer edit section *** (Кошка.ПородаСтрокой Set start)
                this.fПородаСтрокой = value;
                // *** Start programmer edit section *** (Кошка.ПородаСтрокой Set end)

                // *** End programmer edit section *** (Кошка.ПородаСтрокой Set end)
            }
        }
        
        /// <summary>
        /// Агрессивная.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Агрессивная CustomAttributes)

        // *** End programmer edit section *** (Кошка.Агрессивная CustomAttributes)
        public virtual bool Агрессивная
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Агрессивная Get start)

                // *** End programmer edit section *** (Кошка.Агрессивная Get start)
                bool result = this.fАгрессивная;
                // *** Start programmer edit section *** (Кошка.Агрессивная Get end)

                // *** End programmer edit section *** (Кошка.Агрессивная Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Агрессивная Set start)

                // *** End programmer edit section *** (Кошка.Агрессивная Set start)
                this.fАгрессивная = value;
                // *** Start programmer edit section *** (Кошка.Агрессивная Set end)

                // *** End programmer edit section *** (Кошка.Агрессивная Set end)
            }
        }
        
        /// <summary>
        /// КоличествоУсовСлева.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева CustomAttributes)

        // *** End programmer edit section *** (Кошка.КоличествоУсовСлева CustomAttributes)
        [PropertyStorage("КолвоУсовСлева")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt КоличествоУсовСлева
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева Get start)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСлева Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.fКоличествоУсовСлева;
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева Get end)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСлева Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева Set start)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСлева Set start)
                this.fКоличествоУсовСлева = value;
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСлева Set end)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСлева Set end)
            }
        }
        
        /// <summary>
        /// КоличествоУсовСправа.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа CustomAttributes)

        // *** End programmer edit section *** (Кошка.КоличествоУсовСправа CustomAttributes)
        [PropertyStorage("КолвоУсовСправа")]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableInt КоличествоУсовСправа
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа Get start)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСправа Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableInt result = this.fКоличествоУсовСправа;
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа Get end)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСправа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа Set start)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСправа Set start)
                this.fКоличествоУсовСправа = value;
                // *** Start programmer edit section *** (Кошка.КоличествоУсовСправа Set end)

                // *** End programmer edit section *** (Кошка.КоличествоУсовСправа Set end)
            }
        }
        
        /// <summary>
        /// КошкаСтрокой.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.КошкаСтрокой CustomAttributes)

        // *** End programmer edit section *** (Кошка.КошкаСтрокой CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.SQLDataService), "@Кличка@")]
        public virtual string КошкаСтрокой
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.КошкаСтрокой Get)
                return null;
                // *** End programmer edit section *** (Кошка.КошкаСтрокой Get)
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.КошкаСтрокой Set)

                // *** End programmer edit section *** (Кошка.КошкаСтрокой Set)
            }
        }
        
        /// <summary>
        /// Ключ.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Ключ CustomAttributes)

        // *** End programmer edit section *** (Кошка.Ключ CustomAttributes)
        public virtual ICSSoft.STORMNET.KeyGen.KeyGuid Ключ
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Ключ Get start)

                // *** End programmer edit section *** (Кошка.Ключ Get start)
                ICSSoft.STORMNET.KeyGen.KeyGuid result = this.fКлюч;
                // *** Start programmer edit section *** (Кошка.Ключ Get end)

                // *** End programmer edit section *** (Кошка.Ключ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Ключ Set start)

                // *** End programmer edit section *** (Кошка.Ключ Set start)
                this.fКлюч = value;
                // *** Start programmer edit section *** (Кошка.Ключ Set end)

                // *** End programmer edit section *** (Кошка.Ключ Set end)
            }
        }
        
        /// <summary>
        /// Кошка.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Порода CustomAttributes)

        // *** End programmer edit section *** (Кошка.Порода CustomAttributes)
        [PropertyStorage(new string[] {
                "Порода"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.Tests.Порода Порода
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Порода Get start)

                // *** End programmer edit section *** (Кошка.Порода Get start)
                NewPlatform.Flexberry.ORM.Tests.Порода result = this.fПорода;
                // *** Start programmer edit section *** (Кошка.Порода Get end)

                // *** End programmer edit section *** (Кошка.Порода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Порода Set start)

                // *** End programmer edit section *** (Кошка.Порода Set start)
                this.fПорода = value;
                // *** Start programmer edit section *** (Кошка.Порода Set end)

                // *** End programmer edit section *** (Кошка.Порода Set end)
            }
        }
        
        /// <summary>
        /// Кошка.
        /// </summary>
        // *** Start programmer edit section *** (Кошка.Лапа CustomAttributes)

        // *** End programmer edit section *** (Кошка.Лапа CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.Tests.DetailArrayOfЛапа Лапа
        {
            get
            {
                // *** Start programmer edit section *** (Кошка.Лапа Get start)

                // *** End programmer edit section *** (Кошка.Лапа Get start)
                if ((this.fЛапа == null))
                {
                    this.fЛапа = new NewPlatform.Flexberry.ORM.Tests.DetailArrayOfЛапа(this);
                }
                NewPlatform.Flexberry.ORM.Tests.DetailArrayOfЛапа result = this.fЛапа;
                // *** Start programmer edit section *** (Кошка.Лапа Get end)

                // *** End programmer edit section *** (Кошка.Лапа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кошка.Лапа Set start)

                // *** End programmer edit section *** (Кошка.Лапа Set start)
                this.fЛапа = value;
                // *** Start programmer edit section *** (Кошка.Лапа Set end)

                // *** End programmer edit section *** (Кошка.Лапа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "k_КошкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View k_КошкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("k_КошкаE", typeof(NewPlatform.Flexberry.ORM.Tests.Кошка));
                }
            }
            
            /// <summary>
            /// "k_КошкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View k_КошкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("k_КошкаL", typeof(NewPlatform.Flexberry.ORM.Tests.Кошка));
                }
            }
            
            /// <summary>
            /// "КИЛ_КошкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КИЛ_КошкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КИЛ_КошкаE", typeof(NewPlatform.Flexberry.ORM.Tests.Кошка));
                }
            }
            
            /// <summary>
            /// "КИЛ_КошкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КИЛ_КошкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КИЛ_КошкаL", typeof(NewPlatform.Flexberry.ORM.Tests.Кошка));
                }
            }
            
            /// <summary>
            /// "КошкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КошкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КошкаE", typeof(NewPlatform.Flexberry.ORM.Tests.Кошка));
                }
            }
            
            /// <summary>
            /// Представление для тестов над полями типа Guid.
            /// </summary>
            public static ICSSoft.STORMNET.View КошкаGuid
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КошкаGuid", typeof(NewPlatform.Flexberry.ORM.Tests.Кошка));
                }
            }
            
            /// <summary>
            /// "КошкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КошкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КошкаL", typeof(NewPlatform.Flexberry.ORM.Tests.Кошка));
                }
            }
        }
    }
}
