//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// КритерийОценки.
    /// </summary>
    // *** Start programmer edit section *** (КритерийОценки CustomAttributes)

    // *** End programmer edit section *** (КритерийОценки CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КритерийОценкиE", new string[] {
            "ПорядковыйНомер",
            "Описание",
            "Вес",
            "Обязательный"})]
    public class КритерийОценки : ICSSoft.STORMNET.DataObject
    {
        
        private int fПорядковыйНомер;
        
        private string fОписание;
        
        private double fВес;
        
        private bool fОбязательный = false;
        
        private NewPlatform.Flexberry.ORM.Tests.Конкурс fКонкурс;
        
        // *** Start programmer edit section *** (КритерийОценки CustomMembers)

        // *** End programmer edit section *** (КритерийОценки CustomMembers)

        
        /// <summary>
        /// ПорядковыйНомер.
        /// </summary>
        // *** Start programmer edit section *** (КритерийОценки.ПорядковыйНомер CustomAttributes)

        // *** End programmer edit section *** (КритерийОценки.ПорядковыйНомер CustomAttributes)
        public virtual int ПорядковыйНомер
        {
            get
            {
                // *** Start programmer edit section *** (КритерийОценки.ПорядковыйНомер Get start)

                // *** End programmer edit section *** (КритерийОценки.ПорядковыйНомер Get start)
                int result = this.fПорядковыйНомер;
                // *** Start programmer edit section *** (КритерийОценки.ПорядковыйНомер Get end)

                // *** End programmer edit section *** (КритерийОценки.ПорядковыйНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КритерийОценки.ПорядковыйНомер Set start)

                // *** End programmer edit section *** (КритерийОценки.ПорядковыйНомер Set start)
                this.fПорядковыйНомер = value;
                // *** Start programmer edit section *** (КритерийОценки.ПорядковыйНомер Set end)

                // *** End programmer edit section *** (КритерийОценки.ПорядковыйНомер Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (КритерийОценки.Описание CustomAttributes)

        // *** End programmer edit section *** (КритерийОценки.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (КритерийОценки.Описание Get start)

                // *** End programmer edit section *** (КритерийОценки.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (КритерийОценки.Описание Get end)

                // *** End programmer edit section *** (КритерийОценки.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КритерийОценки.Описание Set start)

                // *** End programmer edit section *** (КритерийОценки.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (КритерийОценки.Описание Set end)

                // *** End programmer edit section *** (КритерийОценки.Описание Set end)
            }
        }
        
        /// <summary>
        /// Вес.
        /// </summary>
        // *** Start programmer edit section *** (КритерийОценки.Вес CustomAttributes)

        // *** End programmer edit section *** (КритерийОценки.Вес CustomAttributes)
        public virtual double Вес
        {
            get
            {
                // *** Start programmer edit section *** (КритерийОценки.Вес Get start)

                // *** End programmer edit section *** (КритерийОценки.Вес Get start)
                double result = this.fВес;
                // *** Start programmer edit section *** (КритерийОценки.Вес Get end)

                // *** End programmer edit section *** (КритерийОценки.Вес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КритерийОценки.Вес Set start)

                // *** End programmer edit section *** (КритерийОценки.Вес Set start)
                this.fВес = value;
                // *** Start programmer edit section *** (КритерийОценки.Вес Set end)

                // *** End programmer edit section *** (КритерийОценки.Вес Set end)
            }
        }
        
        /// <summary>
        /// Обязательный.
        /// </summary>
        // *** Start programmer edit section *** (КритерийОценки.Обязательный CustomAttributes)

        // *** End programmer edit section *** (КритерийОценки.Обязательный CustomAttributes)
        public virtual bool Обязательный
        {
            get
            {
                // *** Start programmer edit section *** (КритерийОценки.Обязательный Get start)

                // *** End programmer edit section *** (КритерийОценки.Обязательный Get start)
                bool result = this.fОбязательный;
                // *** Start programmer edit section *** (КритерийОценки.Обязательный Get end)

                // *** End programmer edit section *** (КритерийОценки.Обязательный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КритерийОценки.Обязательный Set start)

                // *** End programmer edit section *** (КритерийОценки.Обязательный Set start)
                this.fОбязательный = value;
                // *** Start programmer edit section *** (КритерийОценки.Обязательный Set end)

                // *** End programmer edit section *** (КритерийОценки.Обязательный Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.Tests.Конкурс.
        /// </summary>
        // *** Start programmer edit section *** (КритерийОценки.Конкурс CustomAttributes)

        // *** End programmer edit section *** (КритерийОценки.Конкурс CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.Tests.Конкурс Конкурс
        {
            get
            {
                // *** Start programmer edit section *** (КритерийОценки.Конкурс Get start)

                // *** End programmer edit section *** (КритерийОценки.Конкурс Get start)
                NewPlatform.Flexberry.ORM.Tests.Конкурс result = this.fКонкурс;
                // *** Start programmer edit section *** (КритерийОценки.Конкурс Get end)

                // *** End programmer edit section *** (КритерийОценки.Конкурс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КритерийОценки.Конкурс Set start)

                // *** End programmer edit section *** (КритерийОценки.Конкурс Set start)
                this.fКонкурс = value;
                // *** Start programmer edit section *** (КритерийОценки.Конкурс Set end)

                // *** End programmer edit section *** (КритерийОценки.Конкурс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КритерийОценкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КритерийОценкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КритерийОценкиE", typeof(NewPlatform.Flexberry.ORM.Tests.КритерийОценки));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of КритерийОценки.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfКритерийОценки CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfКритерийОценки CustomAttributes)
    public class DetailArrayOfКритерийОценки : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.Tests.DetailArrayOfКритерийОценки members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.Tests.DetailArrayOfКритерийОценки members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type КритерийОценки by index.
        /// </summary>
        /// <summary>
        /// Adds object with type КритерийОценки.
        /// </summary>
        public DetailArrayOfКритерийОценки(NewPlatform.Flexberry.ORM.Tests.Конкурс fКонкурс) : 
                base(typeof(КритерийОценки), ((ICSSoft.STORMNET.DataObject)(fКонкурс)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.Tests.КритерийОценки this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.Tests.КритерийОценки)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.Tests.КритерийОценки dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
