//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Личность.
    /// </summary>
    // *** Start programmer edit section *** (Личность CustomAttributes)

    // *** End programmer edit section *** (Личность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛичностьE", new string[] {
            "ФИО"})]
    [View("ЛичностьL", new string[] {
            "ФИО"})]
    public class Личность : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        // *** Start programmer edit section *** (Личность CustomMembers)

        // *** End programmer edit section *** (Личность CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Личность.ФИО CustomAttributes)

        // *** End programmer edit section *** (Личность.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Личность.ФИО Get start)

                // *** End programmer edit section *** (Личность.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Личность.ФИО Get end)

                // *** End programmer edit section *** (Личность.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Личность.ФИО Set start)

                // *** End programmer edit section *** (Личность.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Личность.ФИО Set end)

                // *** End programmer edit section *** (Личность.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЛичностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛичностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛичностьE", typeof(NewPlatform.Flexberry.ORM.Tests.Личность));
                }
            }
            
            /// <summary>
            /// "ЛичностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛичностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛичностьL", typeof(NewPlatform.Flexberry.ORM.Tests.Личность));
                }
            }
        }
    }
}
