//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пол.
    /// </summary>
    // *** Start programmer edit section *** (Пол CustomAttributes)

    // *** End programmer edit section *** (Пол CustomAttributes)
    public enum Пол
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Пол.Мужской CustomAttributes)

        // *** End programmer edit section *** (Пол.Мужской CustomAttributes)
        Мужской,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Пол.Женский CustomAttributes)

        // *** End programmer edit section *** (Пол.Женский CustomAttributes)
        Женский,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Пол.НеПонятно CustomAttributes)

        // *** End programmer edit section *** (Пол.НеПонятно CustomAttributes)
        [Caption("")]
        НеПонятно,
    }
}
