//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние.
    /// </summary>
    // *** Start programmer edit section *** (Состояние CustomAttributes)

    // *** End programmer edit section *** (Состояние CustomAttributes)
    public enum Состояние
    {
        
        // *** Start programmer edit section *** (Состояние.НеНачат CustomAttributes)

        // *** End programmer edit section *** (Состояние.НеНачат CustomAttributes)
        НеНачат,
        
        // *** Start programmer edit section *** (Состояние.СборИдей CustomAttributes)

        // *** End programmer edit section *** (Состояние.СборИдей CustomAttributes)
        СборИдей,
        
        // *** Start programmer edit section *** (Состояние.ЭкспертнаяОценка CustomAttributes)

        // *** End programmer edit section *** (Состояние.ЭкспертнаяОценка CustomAttributes)
        ЭкспертнаяОценка,
        
        // *** Start programmer edit section *** (Состояние.Завершён CustomAttributes)

        // *** End programmer edit section *** (Состояние.Завершён CustomAttributes)
        Завершён,
        
        // *** Start programmer edit section *** (Состояние.Отменён CustomAttributes)

        // *** End programmer edit section *** (Состояние.Отменён CustomAttributes)
        Отменён,
    }
}
