//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сторона.
    /// </summary>
    // *** Start programmer edit section *** (Сторона CustomAttributes)

    // *** End programmer edit section *** (Сторона CustomAttributes)
    public enum Сторона
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Сторона.НетЗначения CustomAttributes)

        // *** End programmer edit section *** (Сторона.НетЗначения CustomAttributes)
        НетЗначения,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Сторона.Левая CustomAttributes)

        // *** End programmer edit section *** (Сторона.Левая CustomAttributes)
        Левая,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (Сторона.Правая CustomAttributes)

        // *** End programmer edit section *** (Сторона.Правая CustomAttributes)
        Правая,
    }
}
