//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип кошки.
    /// </summary>
    // *** Start programmer edit section *** (ТипКошки CustomAttributes)

    // *** End programmer edit section *** (ТипКошки CustomAttributes)
    public enum ТипКошки
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипКошки.НетЗначения CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.НетЗначения CustomAttributes)
        [Caption("")]
        НетЗначения,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипКошки.Дикая CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.Дикая CustomAttributes)
        [Caption("Дикая")]
        Дикая,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипКошки.Домашняя CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.Домашняя CustomAttributes)
        [Caption("Домашняя")]
        Домашняя,
    }
}
