//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// УчастникХозДоговора.
    /// </summary>
    // *** Start programmer edit section *** (УчастникХозДоговора CustomAttributes)

    // *** End programmer edit section *** (УчастникХозДоговора CustomAttributes)
    [ClassStorage("УчастникХозДог")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчастникХозДоговораE", new string[] {
            "НомерУчастникаХозДоговора",
            "Личность",
            "Личность.ФИО"}, Hidden=new string[] {
            "Личность.ФИО"})]
    public class УчастникХозДоговора : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерУчастникаХозДоговора;
        
        private NewPlatform.Flexberry.ORM.Tests.tСтатусИсполнителяХозДоговора fСтатус;
        
        private NewPlatform.Flexberry.ORM.Tests.Личность fЛичность;
        
        private NewPlatform.Flexberry.ORM.Tests.ХозДоговор fХозДоговор;
        
        // *** Start programmer edit section *** (УчастникХозДоговора CustomMembers)

        // *** End programmer edit section *** (УчастникХозДоговора CustomMembers)

        
        /// <summary>
        /// НомерУчастникаХозДоговора.
        /// </summary>
        // *** Start programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора CustomAttributes)

        // *** End programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора CustomAttributes)
        [PropertyStorage("НомУчастнХозДог")]
        public virtual int НомерУчастникаХозДоговора
        {
            get
            {
                // *** Start programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора Get start)

                // *** End programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора Get start)
                int result = this.fНомерУчастникаХозДоговора;
                // *** Start programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора Get end)

                // *** End programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора Set start)

                // *** End programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора Set start)
                this.fНомерУчастникаХозДоговора = value;
                // *** Start programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора Set end)

                // *** End programmer edit section *** (УчастникХозДоговора.НомерУчастникаХозДоговора Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (УчастникХозДоговора.Статус CustomAttributes)

        // *** End programmer edit section *** (УчастникХозДоговора.Статус CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.Tests.tСтатусИсполнителяХозДоговора Статус
        {
            get
            {
                // *** Start programmer edit section *** (УчастникХозДоговора.Статус Get start)

                // *** End programmer edit section *** (УчастникХозДоговора.Статус Get start)
                NewPlatform.Flexberry.ORM.Tests.tСтатусИсполнителяХозДоговора result = this.fСтатус;
                // *** Start programmer edit section *** (УчастникХозДоговора.Статус Get end)

                // *** End programmer edit section *** (УчастникХозДоговора.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастникХозДоговора.Статус Set start)

                // *** End programmer edit section *** (УчастникХозДоговора.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (УчастникХозДоговора.Статус Set end)

                // *** End programmer edit section *** (УчастникХозДоговора.Статус Set end)
            }
        }
        
        /// <summary>
        /// УчастникХозДоговора.
        /// </summary>
        // *** Start programmer edit section *** (УчастникХозДоговора.Личность CustomAttributes)

        // *** End programmer edit section *** (УчастникХозДоговора.Личность CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.Tests.Личность Личность
        {
            get
            {
                // *** Start programmer edit section *** (УчастникХозДоговора.Личность Get start)

                // *** End programmer edit section *** (УчастникХозДоговора.Личность Get start)
                NewPlatform.Flexberry.ORM.Tests.Личность result = this.fЛичность;
                // *** Start programmer edit section *** (УчастникХозДоговора.Личность Get end)

                // *** End programmer edit section *** (УчастникХозДоговора.Личность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастникХозДоговора.Личность Set start)

                // *** End programmer edit section *** (УчастникХозДоговора.Личность Set start)
                this.fЛичность = value;
                // *** Start programmer edit section *** (УчастникХозДоговора.Личность Set end)

                // *** End programmer edit section *** (УчастникХозДоговора.Личность Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.Tests.ХозДоговор.
        /// </summary>
        // *** Start programmer edit section *** (УчастникХозДоговора.ХозДоговор CustomAttributes)

        // *** End programmer edit section *** (УчастникХозДоговора.ХозДоговор CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.Tests.ХозДоговор ХозДоговор
        {
            get
            {
                // *** Start programmer edit section *** (УчастникХозДоговора.ХозДоговор Get start)

                // *** End programmer edit section *** (УчастникХозДоговора.ХозДоговор Get start)
                NewPlatform.Flexberry.ORM.Tests.ХозДоговор result = this.fХозДоговор;
                // *** Start programmer edit section *** (УчастникХозДоговора.ХозДоговор Get end)

                // *** End programmer edit section *** (УчастникХозДоговора.ХозДоговор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастникХозДоговора.ХозДоговор Set start)

                // *** End programmer edit section *** (УчастникХозДоговора.ХозДоговор Set start)
                this.fХозДоговор = value;
                // *** Start programmer edit section *** (УчастникХозДоговора.ХозДоговор Set end)

                // *** End programmer edit section *** (УчастникХозДоговора.ХозДоговор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УчастникХозДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастникХозДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастникХозДоговораE", typeof(NewPlatform.Flexberry.ORM.Tests.УчастникХозДоговора));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of УчастникХозДоговора.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУчастникХозДоговора CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУчастникХозДоговора CustomAttributes)
    public class DetailArrayOfУчастникХозДоговора : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.Tests.DetailArrayOfУчастникХозДоговора members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.Tests.DetailArrayOfУчастникХозДоговора members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type УчастникХозДоговора by index.
        /// </summary>
        /// <summary>
        /// Adds object with type УчастникХозДоговора.
        /// </summary>
        public DetailArrayOfУчастникХозДоговора(NewPlatform.Flexberry.ORM.Tests.ХозДоговор fХозДоговор) : 
                base(typeof(УчастникХозДоговора), ((ICSSoft.STORMNET.DataObject)(fХозДоговор)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.Tests.УчастникХозДоговора this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.Tests.УчастникХозДоговора)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.Tests.УчастникХозДоговора dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
