//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Flexberry.ORM.Tests")]
[assembly: System.Reflection.AssemblyDescription("Flexberry.ORM.Tests")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("NewPlatform")]
[assembly: System.Reflection.AssemblyProduct("Flexberry.ORM.Tests")]
[assembly: System.Reflection.AssemblyCopyright("(c) 2004-2015. NewPlatform Ltd. All rights reserved.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Reflection.AssemblyKeyName("")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.1")]
[assembly: System.Reflection.AssemblyKeyFile("")]

