//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// InformationTestClassChild.
    /// </summary>
    // *** Start programmer edit section *** (InformationTestClassChild CustomAttributes)

    // *** End programmer edit section *** (InformationTestClassChild CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class InformationTestClassChild : NewPlatform.Flexberry.ORM.Tests.InformationTestClass
    {
        
        // *** Start programmer edit section *** (InformationTestClassChild CustomMembers)

        // *** End programmer edit section *** (InformationTestClassChild CustomMembers)

        
        /// <summary>
        /// PublicStringProperty.
        /// </summary>
        // *** Start programmer edit section *** (InformationTestClassChild.PublicStringProperty CustomAttributes)

        // *** End programmer edit section *** (InformationTestClassChild.PublicStringProperty CustomAttributes)
        [StrLen(255)]
        [DataServiceExpression(typeof(ICSSoft.STORMNET.Business.MSSQLDataService), "TestDataServiceExpressionChild")]
        public override string PublicStringProperty
        {
            get
            {
                // *** Start programmer edit section *** (InformationTestClassChild.PublicStringProperty Get start)

                // *** End programmer edit section *** (InformationTestClassChild.PublicStringProperty Get start)
                string result = base.PublicStringProperty;
                // *** Start programmer edit section *** (InformationTestClassChild.PublicStringProperty Get end)

                // *** End programmer edit section *** (InformationTestClassChild.PublicStringProperty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InformationTestClassChild.PublicStringProperty Set start)

                // *** End programmer edit section *** (InformationTestClassChild.PublicStringProperty Set start)
                base.PublicStringProperty = value;
                // *** Start programmer edit section *** (InformationTestClassChild.PublicStringProperty Set end)

                // *** End programmer edit section *** (InformationTestClassChild.PublicStringProperty Set end)
            }
        }
    }
}
