//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NumberedYear.
    /// </summary>
    // *** Start programmer edit section *** (NumberedYear CustomAttributes)

    // *** End programmer edit section *** (NumberedYear CustomAttributes)
    public enum NumberedYear
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (NumberedYear.Year2011 CustomAttributes)

        // *** End programmer edit section *** (NumberedYear.Year2011 CustomAttributes)
        [Caption("2011")]
        Year2011,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (NumberedYear.Year2012 CustomAttributes)

        // *** End programmer edit section *** (NumberedYear.Year2012 CustomAttributes)
        [Caption("2012")]
        Year2012,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (NumberedYear.Year2013 CustomAttributes)

        // *** End programmer edit section *** (NumberedYear.Year2013 CustomAttributes)
        [Caption("2013")]
        Year2013,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (NumberedYear.Year2014 CustomAttributes)

        // *** End programmer edit section *** (NumberedYear.Year2014 CustomAttributes)
        [Caption("")]
        Year2014,
    }
}
