//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// tСтатусИсполнителяХозДоговора.
    /// </summary>
    // *** Start programmer edit section *** (tСтатусИсполнителяХозДоговора CustomAttributes)

    // *** End programmer edit section *** (tСтатусИсполнителяХозДоговора CustomAttributes)
    public enum tСтатусИсполнителяХозДоговора
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tСтатусИсполнителяХозДоговора.Руководитель CustomAttributes)

        // *** End programmer edit section *** (tСтатусИсполнителяХозДоговора.Руководитель CustomAttributes)
        Руководитель,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tСтатусИсполнителяХозДоговора.Никто CustomAttributes)

        // *** End programmer edit section *** (tСтатусИсполнителяХозДоговора.Никто CustomAttributes)
        Никто,
    }
}
