//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.Tests
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ВидКредита.
    /// </summary>
    // *** Start programmer edit section *** (ВидКредита CustomAttributes)

    // *** End programmer edit section *** (ВидКредита CustomAttributes)
    public enum ВидКредита
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ВидКредита.Потребительский CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Потребительский CustomAttributes)
        Потребительский,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ВидКредита.Автокредит CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Автокредит CustomAttributes)
        Автокредит,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ВидКредита.Ипотека CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Ипотека CustomAttributes)
        Ипотека,
    }
}
