//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestClassesForPostgres
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Class_float.
    /// </summary>
    // *** Start programmer edit section *** (Class_float CustomAttributes)

    // *** End programmer edit section *** (Class_float CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Class_float : ICSSoft.STORMNET.DataObject
    {
        
        private float fAttr;
        
        // *** Start programmer edit section *** (Class_float CustomMembers)

        // *** End programmer edit section *** (Class_float CustomMembers)

        
        /// <summary>
        /// Attr.
        /// </summary>
        // *** Start programmer edit section *** (Class_float.Attr CustomAttributes)

        // *** End programmer edit section *** (Class_float.Attr CustomAttributes)
        public virtual float Attr
        {
            get
            {
                // *** Start programmer edit section *** (Class_float.Attr Get start)

                // *** End programmer edit section *** (Class_float.Attr Get start)
                float result = this.fAttr;
                // *** Start programmer edit section *** (Class_float.Attr Get end)

                // *** End programmer edit section *** (Class_float.Attr Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class_float.Attr Set start)

                // *** End programmer edit section *** (Class_float.Attr Set start)
                this.fAttr = value;
                // *** Start programmer edit section *** (Class_float.Attr Set end)

                // *** End programmer edit section *** (Class_float.Attr Set end)
            }
        }
    }
}
