//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestClassesForPostgres
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ДочернийКлассДлинноеИмя.
    /// </summary>
    // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя CustomAttributes)

    // *** End programmer edit section *** (ДочернийКлассДлинноеИмя CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TestView1", new string[] {
            "Атрибут3",
            "МастерКлассДлинноеИмя01.АтрибутМастерКласса01",
            "МастерКлассДлинноеИмя01"}, Hidden=new string[] {
            "МастерКлассДлинноеИмя01"})]
    [View("TestView2", new string[] {
            "Атрибут3",
            "МастерКлассДлинноеИмя01.АтрибутМастерКласса02",
            "МастерКлассДлинноеИмя01"}, Hidden=new string[] {
            "МастерКлассДлинноеИмя01"})]
    public class ДочернийКлассДлинноеИмя : IIS.TestClassesForPostgres.РодительскийКлассДлинноеИмя
    {
        
        private IIS.TestClassesForPostgres.МастерКлассДлинноеИмя fМастерКлассДлинноеИмя01;
        
        private IIS.TestClassesForPostgres.МастерКлассДлинноеИмя2 fМастерКлассДлинноеИмя02;
        
        private IIS.TestClassesForPostgres.DetailArrayOfДетейлКлассДлинноеИмя fДетейлКлассДлинноеИмя;
        
        // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя CustomMembers)

        // *** End programmer edit section *** (ДочернийКлассДлинноеИмя CustomMembers)

        
        /// <summary>
        /// ДочернийКлассДлинноеИмя.
        /// </summary>
        // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 CustomAttributes)

        // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 CustomAttributes)
        [PropertyStorage("МастерКлассДлинноеИмя01")]
        [TypeUsage(new string[] {
                "IIS.TestClassesForPostgres.МастерКлассДлинноеИмя",
                "IIS.TestClassesForPostgres.МастерКлассДлинноеИмя2"})]
        [NotNull()]
        public virtual IIS.TestClassesForPostgres.МастерКлассДлинноеИмя МастерКлассДлинноеИмя01
        {
            get
            {
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 Get start)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 Get start)
                IIS.TestClassesForPostgres.МастерКлассДлинноеИмя result = this.fМастерКлассДлинноеИмя01;
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 Get end)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 Set start)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 Set start)
                this.fМастерКлассДлинноеИмя01 = value;
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 Set end)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя01 Set end)
            }
        }
        
        /// <summary>
        /// ДочернийКлассДлинноеИмя.
        /// </summary>
        // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 CustomAttributes)

        // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 CustomAttributes)
        [PropertyStorage(new string[] {
                "МастерКлассДлинноеИмя02"})]
        [NotNull()]
        public virtual IIS.TestClassesForPostgres.МастерКлассДлинноеИмя2 МастерКлассДлинноеИмя02
        {
            get
            {
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 Get start)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 Get start)
                IIS.TestClassesForPostgres.МастерКлассДлинноеИмя2 result = this.fМастерКлассДлинноеИмя02;
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 Get end)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 Set start)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 Set start)
                this.fМастерКлассДлинноеИмя02 = value;
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 Set end)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.МастерКлассДлинноеИмя02 Set end)
            }
        }
        
        /// <summary>
        /// ДочернийКлассДлинноеИмя.
        /// </summary>
        // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя CustomAttributes)

        // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя CustomAttributes)
        [TypeUsage(new System.Type[] {
                typeof(IIS.TestClassesForPostgres.ДетейлКлассДлинноеИмя),
                typeof(IIS.TestClassesForPostgres.ДетейлКлассДлинноеИмя2)})]
        public virtual IIS.TestClassesForPostgres.DetailArrayOfДетейлКлассДлинноеИмя ДетейлКлассДлинноеИмя
        {
            get
            {
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя Get start)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя Get start)
                if ((this.fДетейлКлассДлинноеИмя == null))
                {
                    this.fДетейлКлассДлинноеИмя = new IIS.TestClassesForPostgres.DetailArrayOfДетейлКлассДлинноеИмя(this);
                }
                IIS.TestClassesForPostgres.DetailArrayOfДетейлКлассДлинноеИмя result = this.fДетейлКлассДлинноеИмя;
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя Get end)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя Set start)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя Set start)
                this.fДетейлКлассДлинноеИмя = value;
                // *** Start programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя Set end)

                // *** End programmer edit section *** (ДочернийКлассДлинноеИмя.ДетейлКлассДлинноеИмя Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TestView1" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TestView1
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TestView1", typeof(IIS.TestClassesForPostgres.ДочернийКлассДлинноеИмя));
                }
            }
            
            /// <summary>
            /// "TestView2" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TestView2
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TestView2", typeof(IIS.TestClassesForPostgres.ДочернийКлассДлинноеИмя));
                }
            }
        }
    }
}
