//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestClassesForPostgres
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// РодительскийКлассДлинноеИмя.
    /// </summary>
    // *** Start programmer edit section *** (РодительскийКлассДлинноеИмя CustomAttributes)

    // *** End programmer edit section *** (РодительскийКлассДлинноеИмя CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class РодительскийКлассДлинноеИмя : IIS.TestClassesForPostgres.MyClass
    {
        
        // *** Start programmer edit section *** (РодительскийКлассДлинноеИмя CustomMembers)

        // *** End programmer edit section *** (РодительскийКлассДлинноеИмя CustomMembers)

    }
}
