var class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_validation_1_1_exceptions_1_1_invalid_parameter_type_validation_exception =
[
    [ "InvalidParameterTypeValidationException", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_validation_1_1_exceptions_1_1_invalid_parameter_type_validation_exception.html#acc5dfa7c039dd2fe7d6f56c545fa04dd", null ]
];