var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_tests_1_1_i_c_s_soft_1_1_s_t_o_r_m_n_e_t =
[
    [ "Business", "namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_tests_1_1_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business.html", "namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_tests_1_1_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business" ],
    [ "DataObject", "namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_tests_1_1_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_data_object.html", "namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_tests_1_1_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_data_object" ]
];