var namespace_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_tests_1_1_test_classes_1_1_business =
[
    [ "PrimaryKeyStorageTest", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_tests_1_1_test_classes_1_1_business_1_1_primary_key_storage_test.html", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_tests_1_1_test_classes_1_1_business_1_1_primary_key_storage_test" ],
    [ "SecondLoadObjectTest", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_tests_1_1_test_classes_1_1_business_1_1_second_load_object_test.html", null ],
    [ "UpdateComplexObjectStructTest", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_tests_1_1_test_classes_1_1_business_1_1_update_complex_object_struct_test.html", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_tests_1_1_test_classes_1_1_business_1_1_update_complex_object_struct_test" ]
];