var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_postgres =
[
    [ "PostgresDataServiceTest", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_postgres_1_1_postgres_data_service_test.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_integrated_tests_1_1_postgres_1_1_postgres_data_service_test" ]
];