var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_current_user_service =
[
    [ "CurrentUserExtensions", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_current_user_service_1_1_current_user_extensions.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_current_user_service_1_1_current_user_extensions" ],
    [ "EmptyCurrentUser", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_current_user_service_1_1_empty_current_user.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_current_user_service_1_1_empty_current_user" ],
    [ "ICurrentUser", "interface_new_platform_1_1_flexberry_1_1_o_r_m_1_1_current_user_service_1_1_i_current_user.html", "interface_new_platform_1_1_flexberry_1_1_o_r_m_1_1_current_user_service_1_1_i_current_user" ]
];