var namespace_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests =
[
    [ "BusinessServerOrderTest", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_business_server_order_test.html", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_business_server_order_test" ],
    [ "DataServiceProviderTest", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_data_service_provider_test.html", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_data_service_provider_test" ],
    [ "EnrichViewWithPropertiesUsedInFunctionTest", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_enrich_view_with_properties_used_in_function_test.html", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_enrich_view_with_properties_used_in_function_test" ],
    [ "InterfaceTests", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_interface_tests.html", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_interface_tests" ],
    [ "SQLDataServiceTest", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_s_q_l_data_service_test.html", "class_i_c_s_soft_1_1_s_t_o_r_m_n_e_t_1_1_business_1_1_tests_1_1_s_q_l_data_service_test" ]
];