//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ExternalLanguageDefinition.AdvLimit {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class STORMAdvLimitSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static STORMAdvLimitSettings defaultInstance = ((STORMAdvLimitSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new STORMAdvLimitSettings())));
        
        public static STORMAdvLimitSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
