//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("NewPlatform.Flexberry.ORM.Test(Objects)")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("New Platform Ltd.")]
[assembly: System.Reflection.AssemblyProduct("Flexberry ORM")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © New Platform Ltd. 2017")]
[assembly: System.Reflection.AssemblyTrademark("Flexberry")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Reflection.AssemblyKeyName("")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.1")]

