//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.IntegratedTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewPlatform.Flexberry.ORM.IntegratedTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///CREATE TABLE [InformationTestClass] (
        ///
        ///	 [primaryKey] UNIQUEIDENTIFIER  NOT NULL,
        ///
        ///	 [PublicStringProperty] VARCHAR(255)  NULL,
        ///
        ///	 [StringPropertyForInfTestClass] VARCHAR(255)  NULL,
        ///
        ///	 [IntPropertyForInfTestClass] INT  NULL,
        ///
        ///	 [BoolPropertyForInfTestClass] BIT  NULL,
        ///
        ///	 PRIMARY KEY ([primaryKey]))
        ///
        ///
        ///CREATE TABLE [ТипЛапы] (
        ///
        ///	 [primaryKey] UNIQUEIDENTIFIER  NOT NULL,
        ///
        ///	 [Название] VARCHAR(255)  NULL,
        ///
        ///	 [Актуально] BIT  NULL,
        ///
        ///	 PRIMARY KEY ([primaryKey]))
        ///
        ///
        ///CREATE TABLE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MssqlScript {
            get {
                return ResourceManager.GetString("MssqlScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///CREATE TABLE &quot;InformationTestClass&quot;
        ///(
        ///
        ///	&quot;primaryKey&quot; RAW(16) NOT NULL,
        ///
        ///	&quot;PublicStringProperty&quot; NVARCHAR2(255) NULL,
        ///
        ///	&quot;StringPropertyForInfTestClass&quot; NVARCHAR2(255) NULL,
        ///
        ///	&quot;IntPropertyForInfTestClass&quot; NUMBER(10) NULL,
        ///
        ///	&quot;BoolPropertyForInfTestClass&quot; NUMBER(1) NULL,
        ///
        ///	 PRIMARY KEY (&quot;primaryKey&quot;)
        ///) ;
        ///
        ///
        ///CREATE TABLE &quot;ТипЛапы&quot;
        ///(
        ///
        ///	&quot;primaryKey&quot; RAW(16) NOT NULL,
        ///
        ///	&quot;Название&quot; NVARCHAR2(255) NULL,
        ///
        ///	&quot;Актуально&quot; NUMBER(1) NULL,
        ///
        ///	 PRIMARY KEY (&quot;primaryKey&quot;)
        ///) ;
        ///
        ///
        ///CREATE TABLE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OracleScript {
            get {
                return ResourceManager.GetString("OracleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///CREATE TABLE МастерКлассДлинноеИмя (
        ///
        /// primaryKey UUID NOT NULL,
        ///
        /// АтрибутМастерКласса01 VARCHAR(255) NULL,
        ///
        /// АтрибутМастерКласса02 VARCHAR(255) NULL,
        ///
        /// MasterAttr1 TIMESTAMP(3) NULL,
        ///
        /// MasterAttr2 BOOLEAN NULL,
        ///
        /// MasterRoot UUID NOT NULL,
        ///
        /// PRIMARY KEY (primaryKey));
        ///
        ///
        ///CREATE TABLE Class_ulong (
        ///
        /// primaryKey UUID NOT NULL,
        ///
        /// Attr BIGINT NULL,
        ///
        /// PRIMARY KEY (primaryKey));
        ///
        ///
        ///CREATE TABLE ДочернийКлассДлинноеИмя (
        ///
        /// primaryKey UUID NOT NULL,
        ///
        /// Attr21 TEXT NULL,
        ///
        /// Attr20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostgresDataServiceTestScript {
            get {
                return ResourceManager.GetString("PostgresDataServiceTestScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///CREATE TABLE InformationTestClass (
        ///
        /// primaryKey UUID NOT NULL,
        ///
        /// PublicStringProperty VARCHAR(255) NULL,
        ///
        /// StringPropertyForInfTestClass VARCHAR(255) NULL,
        ///
        /// IntPropertyForInfTestClass INT NULL,
        ///
        /// BoolPropertyForInfTestClass BOOLEAN NULL,
        ///
        /// PRIMARY KEY (primaryKey));
        ///
        ///
        ///CREATE TABLE ТипЛапы (
        ///
        /// primaryKey UUID NOT NULL,
        ///
        /// Название VARCHAR(255) NULL,
        ///
        /// Актуально BOOLEAN NULL,
        ///
        /// PRIMARY KEY (primaryKey));
        ///
        ///
        ///CREATE TABLE Идея (
        ///
        /// primaryKey UUID NOT NULL,
        ///
        /// Заголовок VARCH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostgresScript {
            get {
                return ResourceManager.GetString("PostgresScript", resourceCulture);
            }
        }
    }
}
